In [3]:
#Problem 1
import pritty_print
try:
    pritty_print.semple_print(2)
except Exception:
    print('fv')

ModuleNotFoundError: No module named 'pritty_print'

In [2]:
#Problem 2
def div(x,y):
    assert y!=0, "Can’t divide"
    return x/y
div(2,0)

AssertionError: Can’t divide

In [3]:
#Problem 3
def exampl_func(my_list:list):
    my_sum=0
    sum_of_pairs=[]
    try:
        for i in range(len(my_list)):
            sum_of_pairs.append(my_list[i]+my_list[i+1])
        print('sum of pairs', sum_of_pairs)
    except IndexError:
        print('It is index error')
    except Exception:
        print('It is not index error')

exampl_func([1,2,3])
    

It is index error


In [4]:
#Problem 4
def UpperContent(fileName):
    try:
        myfile=open(fileName,"r")
        for line in myfile:
            print(line.upper())
        myfile.close()
    except Exception:
        print('File is not found')
UpperContent("test.txt")

File is not found


In [5]:
import numpy as np



In [55]:
#Problem 5
np.random.randint(1,10,(3,5))

array([[9, 4, 5, 4, 4],
       [1, 6, 4, 9, 9],
       [8, 8, 4, 5, 5]])

In [6]:
#Problem 6
x=np.zeros(10)
x[5]=3
print(x)

[0. 0. 0. 0. 0. 3. 0. 0. 0. 0.]


In [7]:
#Problem 7
np.arange(3,15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
#Problem 8
x=np.array([1,3,5,2,4,5])
y=x.reshape(2,3)
z=x.reshape(3,2)
print(y)
print(z)
print(x)


[[1 3 5]
 [2 4 5]]
[[1 3]
 [5 2]
 [4 5]]
[1 3 5 2 4 5]


In [9]:
#Problem 9
def func1(x):
    while (sum(x)/len(x))>5:
        x=x/2
    print(x)

func1(np.array([9,5,8,9,6]))    


[4.5 2.5 4.  4.5 3. ]


In [10]:
#Problem 10.1
def func2(x):
    for i in range(x.shape[1]):
        print (x[...,i])
b=np.random.randint(1,10,(5,4))
print(b)
func2(b)

[[8 1 5 8]
 [4 1 9 7]
 [3 7 4 9]
 [8 2 1 3]
 [5 3 9 7]]
[8 4 3 8 5]
[1 1 7 2 3]
[5 9 4 1 9]
[8 7 9 3 7]


In [11]:
#Problem 10.2
def func2(x):
    for i in range(x.shape[0]):
        print (x[i])
b=np.random.randint(1,10,(5,4))
print(b)
func2(b)

[[9 5 8 8]
 [8 4 3 8]
 [6 4 3 3]
 [4 7 9 1]
 [3 6 6 3]]
[9 5 8 8]
[8 4 3 8]
[6 4 3 3]
[4 7 9 1]
[3 6 6 3]
